export const inviteConfig = {
  babyName: '도아',
  message: `김도아의 돌잔치에 초대합니다.`,
  eventDateTime: '2026년 3월 7일 (토) 오후 12:00',
  venueName: '신라스테이 동탄',
  address: '경기 화성시 동탄구 노작로 161 신라스테이 동탄 7층',
  kakaoMapUrl: 'https://naver.me/Fuz51F6w',
  galleryImages: [
    '/gallery-1.webp',
    '/gallery-2.webp',
    '/gallery-3.webp',
    '/gallery-4.webp',
    '/gallery-5.webp',
    '/gallery-6.webp',
    '/gallery-7.webp',
    '/gallery-8.webp',
    '/gallery-9.webp',
    '/gallery-10.webp',
    '/gallery-11.webp',
    '/gallery-12.webp',
    '/gallery-13.webp',
    '/gallery-14.webp',
  ],
};
