export const inviteConfig = {
  babyName: '김도아',
  message: `소중한 첫 생일을 맞아 작은 마음을 모아
함께 축하해 주시면 큰 기쁨이 되겠습니다.`,
  eventDateTime: '2026년 3월 7일 (토) 오후 12:00',
  venueName: '신라스테이 동탄',
  address: '경기 화성시 동탄구 노작로 161 신라스테이 동탄 7층',
  kakaoMapUrl: 'https://naver.me/Fuz51F6w',
  contacts: '아빠 010-0000-0000 · 엄마 010-0000-0000',
  galleryImages: [
    '/gallery-1.webp',
    '/gallery-2.webp',
    '/gallery-3.webp',
    '/gallery-4.webp',
    '/gallery-5.webp',
    '/gallery-6.webp',
    '/gallery-7.webp',
    '/gallery-8.webp',
    '/gallery-9.webp',
    '/gallery-10.webp',
    '/gallery-11.webp',
    '/gallery-12.webp',
    '/gallery-13.webp',
    '/gallery-14.webp',
  ],
};
